[log]
  level = "TRACE"

[accessLog]

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[http]
  [http.routers]
    [http.routers.electric]
      rule = "PathPrefix(`/electric`)"
      service = "electric"
      entryPoints = ["web"]
      middlewares = ["stripElectricPrefix", "forwardAuth"]

    [http.routers.todo]
      rule = "PathPrefix(`/`)"
      service = "todo"
      entryPoints = ["web"]

  [http.services]
    [http.services.electric.loadBalancer]
      [[http.services.electric.loadBalancer.servers]]
        url = "http://electric:3000"

    [http.services.todo.loadBalancer]
      [[http.services.todo.loadBalancer.servers]]
        url = "http://host.docker.internal:4000"

  [http.middlewares]
    [http.middlewares.forwardAuth.forwardAuth]
      address = "http://host.docker.internal:4000/electric-authorization"

    [http.middlewares.stripElectricPrefix.stripPrefix]
      prefixes = ["/electric"]

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik.toml"
